#!/usr/bin/env python3
"""
Development Environment Setup Script
Ensures all required environment variables and dependencies are set.
"""

import os
import sys
from pathlib import Path


def setup_environment() -> None:
    """Setup development environment with required environment variables."""
    
    # Read .env.example
    env_example = Path(__file__).parent.parent / ".env.example"
    env_file = Path(__file__).parent.parent / ".env"
    
    if not env_example.exists():
        print("❌ .env.example not found")
        sys.exit(1)
    
    # Load existing .env or create from .env.example
    env_vars = {}
    if env_file.exists():
        with open(env_file) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    env_vars[key.strip()] = value.strip()
    
    # Required defaults for development
    defaults = {
        "SECRET_KEY": "dev-secret-key-change-in-production-12345",
        "TESTING": "true",
        "POSTGRES_PASSWORD": "postgres",
        "DATABASE_URL": "postgresql://postgres:postgres@localhost:5432/enal_ai_os",
        "REDIS_URL": "redis://localhost:6379/0",
        "QDRANT_URL": "http://localhost:6333",
        "OPENAI_API_KEY": "",
        "ANTHROPIC_API_KEY": "",
        "GOOGLE_API_KEY": "",
        "GEMINI_API_KEY": "",
        "OLLAMA_BASE_URL": "http://localhost:11434",
        "DEFAULT_MODEL": "lmstudio/google/gemma-4-4b",
        "DEFAULT_REASONING_MODEL": "lmstudio/google/gemma-4-4b",
        "DEFAULT_EMBEDDING_MODEL": "text-embedding-3-small",
        "MAX_TOKENS": "4096",
        "TEMPERATURE": "0.7",
        "ACCESS_TOKEN_EXPIRE_MINUTES": "11520",
    }
    
    # Merge with defaults
    for key, default_value in defaults.items():
        if key not in env_vars or not env_vars[key]:
            env_vars[key] = default_value
    
    # Write .env file
    with open(env_file, "w") as f:
        f.write("# Auto-generated by setup_dev_environment.py\n")
        f.write("# DO NOT commit this file to version control\n\n")
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print("✅ Development environment configured")
    print(f"   SECRET_KEY: {'*' * 20} (set)")
    print(f"   DATABASE_URL: {env_vars.get('DATABASE_URL')}")
    print(f"   REDIS_URL: {env_vars.get('REDIS_URL')}")
    
    # Set environment variables for current session
    for key, value in env_vars.items():
        os.environ[key] = value


if __name__ == "__main__":
    setup_environment()
